### ISSUE TITLE
v3.0.0 makes Sublime unusable

### ISSUE THREAD

**Issue by timiyay** [23maverick23/sublime-jekyll#70]
### Summary of issue

Today, `sublime-jekyll` auto-updated to v3.0.0. After re-opening Sublime later the same day, Jekyll started showing an alert box on a continuous loop, no matter how many times I click `OK`. 

Sublime Text was unusable - I had to race the gap between the alert boxes appearing, to quickly `Remove Packages > Jekyll`.

The error related to a templates directory not existing. The plugin update message _did_ warn me to check my settings. Nonetheless, I'm not even working on a Jekyll project right now, so I expect Sublime to still be functional

### System details

- System Platform?: OSX 10.11.5
- Sublime Version? 3114

### Sublime console output

```
error: Jekyll: Unable to resolve path information!

Path "User/Jekyll Templates" does not exist for "_templates" directory.

Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the `jekyll_auto_find_paths` setting.

If you have set your path settings correctly, please copy the console output and create a new issue.

Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 457, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 1076, in is_enabled
  File "./python3.3/genericpath.py", line 18, in exists
    try:
TypeError: can't specify None for path argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 459, in is_enabled_
    ret = self.is_enabled()
  File "jekyll in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Jekyll.sublime-package", line 1076, in is_enabled
  File "./python3.3/genericpath.py", line 18, in exists
    try:
TypeError: can't specify None for path argument
```

![sublime_jekyll_alert](https://cloud.githubusercontent.com/assets/1470250/16706786/a9d1b43c-45fc-11e6-9768-7c2a58ec5b5e.png)

**Comment by 23maverick23** [comment]
Sorry about this - made an update and didn't test from a fresh environment. Creating the directory in your User folder should solve this error.

Curious - does a complete reinstall solve it? If not, I'll push an update tonight to resolve.

**Comment by timiyay** [comment]
@23maverick23 thanks for the reply.

I tried reinstalling, and the error was still occurring. My solution was to uninstall the plugin, as I'm not currently working on a Jekyll site.

**Comment by MetricMike** [comment]
Same issue. Reinstalling the package appears to work, but you need to ignore the "Jekyll" package prior, since it shuts down Package Control completely.

Curiously, I had a "User/Jekyll Templates" folder, but it doesn't look like it was being recognized. It's behind a symlink though, if that matters.

**Comment by techctu** [comment]
Same issue. 

It says `Unable to find for "_templates" directory.` when I press cmd + shift + p, or try to open sublime-jekyll settting, or something else triggers the plugin.

`Please double-check that you have defined absolute paths to your Jekyll directories, or that you have enabled the jekyll_auto_find_paths setting.`

I've set Jekyll and plugin well, jekyll_auto_find_paths is set in user-settings.
